import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
	root: { flex: 1 },
	content: { padding: 18, paddingTop: 58, paddingBottom: 108 },
	topBand: { position: "absolute", top: 0, left: 0, right: 0, height: 252, opacity: 0.78 },
	header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 },
	headerCopy: { flex: 1, minWidth: 0 },
	headerActions: { flexDirection: "row", gap: 8 },
	eyebrow: { fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
	title: { fontSize: 30, lineHeight: 34, fontWeight: "900", letterSpacing: 0, textTransform: "capitalize" },
	iconBtn: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	changeBadge: { position: "absolute", right: -3, top: -3, minWidth: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center", paddingHorizontal: 4 },
	changeBadgeText: { color: "#fff", fontSize: 11, fontWeight: "900" },
	overviewCard: {
		borderWidth: 1,
		borderRadius: 28,
		padding: 16,
		marginBottom: 12,
		shadowOpacity: 0.12,
		shadowRadius: 26,
		shadowOffset: { width: 0, height: 16 },
		elevation: 5,
	},
	overviewTop: { flexDirection: "row", alignItems: "center", gap: 13 },
	dateTile: { width: 72, height: 78, borderRadius: 18, alignItems: "center", justifyContent: "center" },
	dateTileMonth: { fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
	dateTileDay: { fontSize: 34, fontWeight: "900", letterSpacing: 0 },
	overviewCopy: { flex: 1, minWidth: 0 },
	overviewLabel: { fontSize: 13, fontWeight: "800", textTransform: "capitalize" },
	overviewTitle: { marginTop: 3, fontSize: 24, lineHeight: 29, fontWeight: "900", letterSpacing: 0 },
	overviewStats: { flexDirection: "row", gap: 8, marginTop: 14 },
	nextStrip: { minHeight: 58, borderWidth: 1, borderRadius: 16, marginTop: 14, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 10 },
	nextStripLive: { minHeight: 112, paddingVertical: 12, flexDirection: "column", alignItems: "stretch", gap: 10 },
	nextLiveTop: { flexDirection: "row", alignItems: "center", gap: 10 },
	nextLiveMeta: { flexDirection: "row", gap: 8 },
	nextLivePill: { flex: 1, minHeight: 34, borderRadius: 10, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 6 },
	nextLivePillText: { flex: 1, fontSize: 12, fontWeight: "900" },
	nextProgressTrack: { height: 8, borderRadius: 8, overflow: "hidden" },
	nextProgressFill: { height: "100%", borderRadius: 8 },
	nextDot: { width: 10, height: 34, borderRadius: 8 },
	nextCopy: { flex: 1, minWidth: 0 },
	nextLabel: { fontSize: 11, fontWeight: "900", textTransform: "uppercase" },
	nextTitle: { marginTop: 2, fontSize: 15, fontWeight: "900" },
	nextTime: { fontSize: 16, fontWeight: "900" },
	toolbar: { flexDirection: "row", gap: 10, marginBottom: 12 },
	navBtn: { width: 44, height: 44, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	todayBtn: { flex: 1, minHeight: 44, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7, paddingHorizontal: 10 },
	todayText: { fontWeight: "900" },
	roomBtn: { width: 48, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" },
	segment: { flexDirection: "row", padding: 4, borderRadius: 16, marginBottom: 12 },
	segmentItem: { flex: 1, minHeight: 40, borderRadius: 12, alignItems: "center", justifyContent: "center" },
	segmentText: { fontWeight: "900" },
	offline: { borderWidth: 1, borderRadius: 14, padding: 11, flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
	offlineText: { flex: 1, fontSize: 12, fontWeight: "800", lineHeight: 17 },
	roomChange: { borderWidth: 1, borderRadius: 14, padding: 11, flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
	roomChangeBody: { flex: 1, minWidth: 0 },
	roomChangeText: { flex: 1, fontSize: 12, fontWeight: "900", lineHeight: 17 },
	roomChangeHint: { marginTop: 2, fontSize: 11, fontWeight: "800" },
	roomChangeClose: { width: 30, height: 30, alignItems: "center", justifyContent: "center" },
	contextCard: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 },
	contextText: { flex: 1, fontWeight: "900" },
	daysStrip: { gap: 9, paddingBottom: 12 },
	dayPill: { width: 68, minHeight: 92, borderWidth: 1, borderRadius: 20, alignItems: "center", justifyContent: "center", paddingVertical: 8 },
	dayName: { fontSize: 12, fontWeight: "800", textTransform: "capitalize" },
	dayNum: { fontSize: 24, fontWeight: "900", marginTop: 3 },
	dayDots: { height: 9, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 3, marginTop: 6 },
	dayDot: { width: 5, height: 5, borderRadius: 4 },
	dayDotCancelled: { opacity: 0.5 },
	dayCount: { fontSize: 11, fontWeight: "900", marginTop: 3 },
	loader: { marginVertical: 14 },
	error: { marginBottom: 10, fontWeight: "700" },
	emptyCard: { alignItems: "center", gap: 8 },
	emptyTitle: { fontSize: 20, fontWeight: "900" },
	eventCard: { marginBottom: 12, padding: 14, borderRadius: 22 },
	eventCardCancelled: { borderStyle: "dashed", opacity: 0.74 },
	eventCardHighlighted: {
		shadowOpacity: 0.18,
		shadowRadius: 26,
		shadowOffset: { width: 0, height: 16 },
		elevation: 6,
	},
	eventShell: { flexDirection: "row", gap: 13 },
	timeBlock: { width: 64, borderRadius: 16, alignItems: "center", justifyContent: "center", paddingVertical: 10 },
	eventContent: { flex: 1, minWidth: 0 },
	eventTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
	eventIndicators: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", flexWrap: "wrap", gap: 5 },
	eventTime: { fontSize: 16, fontWeight: "900" },
	eventEnd: { marginTop: 4, fontSize: 12, fontWeight: "900" },
	eventTitle: { fontSize: 18, lineHeight: 23, fontWeight: "900", marginTop: 9 },
	eventTitleCancelled: { textDecorationLine: "line-through" },
	meta: { marginTop: 6, lineHeight: 19 },
	eventMetaGrid: { marginTop: 2 },
	inlineMeta: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 9 },
	inlineText: { flex: 1, fontWeight: "700" },
	typeChip: { maxWidth: 150, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5 },
	typeText: { fontSize: 11, fontWeight: "900" },
	cancelledChip: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 8, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 5 },
	cancelledText: { fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
	onlineChip: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 },
	onlineText: { fontSize: 12, fontWeight: "900" },
	noteIndicator: { flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 8, paddingHorizontal: 7, paddingVertical: 5 },
	noteIndicatorText: { fontSize: 12, fontWeight: "900" },
	noteIconIndicator: { width: 27, height: 27, borderRadius: 8, alignItems: "center", justifyContent: "center" },
	nowBar: { height: 24, borderRadius: 8, overflow: "hidden", marginTop: 11, justifyContent: "center" },
	nowFill: { position: "absolute", left: 0, top: 0, bottom: 0, width: "100%", borderRadius: 8, zIndex: 0 },
	nowText: { alignSelf: "flex-start", marginLeft: 7, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 2, fontSize: 11, fontWeight: "900", zIndex: 1, elevation: 1 },
	modalRoot: { flex: 1 },
	modalHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 12, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
	modalTitle: { fontSize: 24, fontWeight: "900" },
	changeModalTitleWrap: { flex: 1, minWidth: 0, paddingRight: 12 },
	changeModalSubtitle: { marginTop: 3, fontSize: 12, fontWeight: "800" },
	changeHistoryList: { padding: 18, gap: 12, paddingBottom: 108 },
	changeCard: { gap: 12 },
	changeCardHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
	changeKindIcon: { width: 38, height: 38, borderRadius: 8, alignItems: "center", justifyContent: "center" },
	changeCardTitleWrap: { flex: 1, minWidth: 0 },
	changeCardTitle: { fontSize: 16, lineHeight: 21, fontWeight: "900" },
	changeCardMeta: { marginTop: 3, fontSize: 12, fontWeight: "800", textTransform: "capitalize" },
	changeDetails: { gap: 8 },
	changeDetailRow: { borderRadius: 8, padding: 10, gap: 6 },
	changeDetailLabel: { fontSize: 11, fontWeight: "900", textTransform: "uppercase" },
	changeValues: { flexDirection: "row", alignItems: "center", gap: 8 },
	changeValue: { flex: 1, fontSize: 13, lineHeight: 18, fontWeight: "800" },
	changeArrow: { fontSize: 13, fontWeight: "900" },
	changeModalFooter: { position: "absolute", left: 0, right: 0, bottom: 0, padding: 18, borderTopWidth: 1 },
	clearChangesBtn: { minHeight: 50, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
	clearChangesText: { color: "#fff", fontWeight: "900" },
	searchBox: { margin: 18, marginBottom: 8, borderWidth: 1, borderRadius: 16, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 },
	searchInput: { flex: 1, minHeight: 46, fontSize: 16 },
	modalMeta: { marginHorizontal: 18, marginBottom: 10, fontWeight: "700" },
	modalList: { padding: 18, gap: 12, paddingBottom: 48 },
	groupRow: { borderWidth: 1, borderRadius: 14, padding: 13, flexDirection: "row", alignItems: "center", gap: 10 },
	check: { width: 22, height: 22, borderWidth: 1, borderRadius: 6, alignItems: "center", justifyContent: "center" },
	groupName: { flex: 1, fontWeight: "800" },
	modalColorBadge: { alignSelf: "flex-start", borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, marginBottom: 12 },
	mapBtn: { width: 44, height: 42, borderRadius: 8, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	stepper: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 12 },
	stepBtn: { width: 44, height: 42, borderRadius: 8, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	stepText: { fontSize: 22, fontWeight: "900" },
	durationText: { flex: 1, textAlign: "center", fontSize: 20, fontWeight: "900" },
	input: { borderWidth: 1, borderRadius: 8, minHeight: 46, paddingHorizontal: 12, fontSize: 16 },
	primaryBtn: { minHeight: 50, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
	primaryText: { color: "#fff", fontWeight: "900" },
	roomCard: { marginTop: 0 },
	roomFinderScroll: { padding: 18, gap: 14, paddingBottom: 56 },
	roomHeroCard: {
		borderWidth: 1,
		borderRadius: 28,
		padding: 18,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOpacity: 0.1,
		shadowRadius: 22,
		shadowOffset: { width: 0, height: 14 },
		elevation: 5,
	},
	roomHeroGlow: { position: "absolute", right: -56, top: -52, width: 154, height: 154, borderRadius: 90, opacity: 0.9 },
	roomHeroTop: { flexDirection: "row", alignItems: "center", gap: 13 },
	roomHeroIcon: { width: 54, height: 54, borderRadius: 18, alignItems: "center", justifyContent: "center" },
	roomHeroCopy: { flex: 1, minWidth: 0 },
	roomHeroEyebrow: { fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.5 },
	roomHeroTitle: { marginTop: 3, fontSize: 23, lineHeight: 28, fontWeight: "900" },
	roomHeroText: { marginTop: 12, fontSize: 14, lineHeight: 20, fontWeight: "700" },
	roomHeroStats: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 15 },
	roomHeroStat: { flexDirection: "row", alignItems: "center", gap: 6, minHeight: 34, borderRadius: 12, paddingHorizontal: 10 },
	roomHeroStatText: { fontSize: 12, fontWeight: "900" },
	roomSearchCard: { borderWidth: 1, borderRadius: 24, padding: 14, gap: 14 },
	roomSearchBox: { minHeight: 50, borderWidth: 1, borderRadius: 16, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 },
	roomSearchInput: { flex: 1, minHeight: 48, fontSize: 15, fontWeight: "800" },
	roomDurationHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
	roomSectionTitleWrap: { flexDirection: "row", alignItems: "center", gap: 8 },
	roomSectionTitle: { fontSize: 17, fontWeight: "900" },
	roomResetBtn: { minHeight: 34, borderRadius: 12, borderWidth: 1, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 6 },
	roomResetText: { fontSize: 12, fontWeight: "900" },
	durationGrid: { flexDirection: "row", gap: 8 },
	durationPreset: { flex: 1, minHeight: 42, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	durationPresetText: { fontSize: 13, fontWeight: "900" },
	roomInlineFields: { flexDirection: "row", gap: 10 },
	capacityField: { flex: 0.95, minHeight: 50, borderWidth: 1, borderRadius: 16, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 },
	capacityInput: { flex: 1, minHeight: 48, fontSize: 15, fontWeight: "800" },
	searchRoomBtn: { flex: 1, minHeight: 50, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
	searchRoomText: { color: "#fff", fontSize: 15, fontWeight: "900" },
	roomFilterBlock: { gap: 10 },
	roomFilterTitle: { fontSize: 16, fontWeight: "900" },
	roomFilterRow: { gap: 8, paddingRight: 18, paddingBottom: 2 },
	roomFilterChip: { maxWidth: 190, minHeight: 40, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 13 },
	roomFilterText: { fontSize: 13, fontWeight: "900", textTransform: "capitalize" },
	roomFilterCard: { borderWidth: 1, borderRadius: 22, padding: 14, gap: 12 },
	roomFilterHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
	roomFilterCount: { marginTop: 2, fontSize: 12, fontWeight: "800" },
	roomFilterClearBtn: { minHeight: 32, borderRadius: 11, borderWidth: 1, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5 },
	roomFilterClearText: { fontSize: 12, fontWeight: "900" },
	roomCheckboxGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
	roomCheckboxItem: { width: "48%", minHeight: 42, borderRadius: 14, borderWidth: 1, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", gap: 8 },
	roomCheckboxBox: { width: 20, height: 20, borderRadius: 6, borderWidth: 1, alignItems: "center", justifyContent: "center" },
	roomCheckboxText: { flex: 1, fontSize: 12, fontWeight: "900", textTransform: "capitalize" },
	roomLoadingCard: { borderWidth: 1, borderRadius: 18, padding: 16, flexDirection: "row", alignItems: "center", gap: 10 },
	roomLoadingText: { fontWeight: "800" },
	roomResultHeader: { marginTop: 2, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
	roomResultHeaderCopy: { flex: 1, minWidth: 0 },
	roomResultTitle: { fontSize: 22, fontWeight: "900" },
	roomResultSub: { marginTop: 3, fontSize: 13, fontWeight: "800" },
	roomResultBadge: { minHeight: 30, borderRadius: 12, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5 },
	roomResultBadgeText: { fontSize: 12, fontWeight: "900", textTransform: "uppercase" },
	noRoomCard: { borderWidth: 1, borderRadius: 22, padding: 18, alignItems: "center", gap: 8 },
	noRoomTitle: { fontSize: 18, fontWeight: "900" },
	noRoomText: { textAlign: "center", lineHeight: 19, fontWeight: "700" },
	roomResultCard: {
		borderWidth: 1,
		borderRadius: 22,
		padding: 13,
		flexDirection: "row",
		gap: 12,
		shadowColor: "#000",
		shadowOpacity: 0.07,
		shadowRadius: 18,
		shadowOffset: { width: 0, height: 10 },
		elevation: 3,
	},
	roomResultIcon: { width: 44, height: 44, borderRadius: 16, alignItems: "center", justifyContent: "center" },
	roomResultContent: { flex: 1, minWidth: 0 },
	roomResultTopLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
	roomName: { flex: 1, fontSize: 17, fontWeight: "900" },
	roomCapacityBadge: { flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 10, paddingHorizontal: 8, minHeight: 28 },
	roomCapacityText: { fontSize: 11, fontWeight: "900" },
	roomMetaLine: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8 },
	roomMetaText: { flex: 1, fontSize: 13, fontWeight: "800" },
	roomMetaTags: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
	roomMetaTag: { maxWidth: "100%", minHeight: 30, borderRadius: 10, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5 },
	roomMetaTagText: { maxWidth: 190, fontSize: 12, fontWeight: "900", textTransform: "capitalize" },
	roomActions: { flexDirection: "row", gap: 8, marginTop: 13 },
	roomMapAction: { minHeight: 42, borderRadius: 13, borderWidth: 1, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
	roomMapActionText: { fontSize: 13, fontWeight: "900" },
	roomApplyAction: { flex: 1, minHeight: 42, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
	roomApplyText: { color: "#fff", fontSize: 13, fontWeight: "900" },
});

